# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Minjaes Corne-ish Zen Custom'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corneish_zen_v2_left","corneish_zen_v2_right", "ahokore"]'
      branches: '["caksoylar/zmk/caksoylar/zen-v1+v2+experimental"]'
